# Generated by Django 6.0.3 on 2026-04-07 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Smart Plant', max_length=100)),
                ('pump_status', models.BooleanField(default=False, verbose_name='Water Pump ON/OFF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('soil_moisture', models.FloatField(help_text='0-100%')),
                ('temperature', models.FloatField(help_text='°C')),
                ('humidity', models.FloatField(help_text='0-100%')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='sensors.plant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
