# Generated by Django 6.0.3 on 2026-05-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('schedule', 'Scheduled')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='plant',
            name='moisture_threshold',
            field=models.FloatField(default=30.0, help_text='Turn on pump if soil moisture < this value (%)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='schedule_time',
            field=models.TimeField(blank=True, help_text='Example: 07:00 or 18:30', null=True),
        ),
    ]
