# Generated by Django 6.0.3 on 2026-05-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_plant_mode_plant_moisture_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='schedule_time',
        ),
        migrations.AddField(
            model_name='plant',
            name='last_watered',
            field=models.IntegerField(blank=True, help_text='Timestamp of last watering', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='schedule_duration',
            field=models.IntegerField(default=10, help_text='Pump ON duration (seconds)'),
        ),
        migrations.AddField(
            model_name='plant',
            name='schedule_interval',
            field=models.IntegerField(default=3600, help_text='How often to water (seconds)'),
        ),
    ]
