# Generated by Django 6.0.3 on 2026-05-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_remove_plant_schedule_time_plant_last_watered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='schedule_time',
            field=models.TimeField(blank=True, help_text='Example: 07:00 or 18:30', null=True),
        ),
    ]
